services:
  backend:
    build: .
    ports:
      - "8080:8080"
    command: [ "uv", "run", "--no-sync", "uvicorn", "backend.app:app", "--reload", "--host", "0.0.0.0", "--port", "8080" ]
    volumes:
      - ./backend:/app/backend
    develop:
      watch:
        - action: sync
          path: backend
          target: /app/backend
        - action: rebuild
          path: ./pyproject.toml
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - ./services/minio/data:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
